### PR TITLE
skip banned posts when parsing, because they contain no files

### PR DESCRIPTION
**Pull request by f8upd8**
Allows get_images to work when encountering banned posts without image files.

### CODE REVIEW

**Comment by sinkaroid** [comment]
@MalOMaw could you enable the workflows check in your PR, why the CI is not running? just want to ensure there is no breaking flow with other boorus and we can see the danbooru result

**Comment by sinkaroid** [comment]
Hey, I have test with your flow, I think `is_banned` does not affect at all though, idk why it's still throwing the KeyError despite `i["file_url"]` always there

**Comment by f8upd8** [comment]
Hi, I assume you rewritten and deleted the module? If banned danbooru posts don't affect it, I think we can close the PR

**Comment by sinkaroid** [comment]
Yes, I realized the old version was bad behaviour.
1. intended for async usage but still depends on requests lib #3 
2. injecting query parameters for block image with -{block}* eg: `-furry*` is takes more arguments on each booru, and sometime exceed the limit tags

should be fixed now

**Pull request closed without merging**
